services:

  ###########
  ## Frontend
  ###########
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4443:443"
    volumes:
      - ssl:/etc/ssl/
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health", "--insecure", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_healthy

  ##############
  ## API Gateway
  ##############
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      backend-game:
        condition: service_healthy
      backend-auth:
        condition: service_healthy
      backend-users:
        condition: service_healthy
      backend-stats:
        condition: service_healthy
      backend-presence:
        condition: service_healthy
      # backend-chat:
      #   condition: service_healthy

  ###################
  ## Backend Services
  ###################

  # Auth service
  backend-auth:
    container_name: backend-auth
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    secrets:
      - user-session-private.pem
      - user-session-public.pem
      - game-session-private.pem # TODO: Remove if not needed
      - game-session-public.pem # TODO: Remove if not needed
      - internal-access-private.pem
      - internal-access-public.pem
      - chat-service-client.env
      - game-service-client.env
      - presence-service-client.env
      - stats-service-client.env
      - users-service-client.env
      - google-oauth.env
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      backend-redis:
        condition: service_healthy

  backend-redis:
    container_name: backend-redis
    image: "redis:7.0-alpine"
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli ping > /dev/null 2>&1"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  backend-game:
    container_name: backend-game
    build:
      context: ./backend/game
      dockerfile: Dockerfile
    volumes:
      - game_sessions:/app/data
    secrets:
      - game-service-client.env
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  backend-users:
    container_name: backend-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    volumes:
      - users:/app/data
    secrets:
      - users-service-client.env
    # env_file: .env
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  
  backend-presence:
    container_name: backend-presence
    build:
      context: ./backend/presence
      dockerfile: Dockerfile
    secrets:
      - presence-service-client.env
    # env_file: .env
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      backend-redis:
        condition: service_healthy

  backend-stats:
    container_name: backend-stats
    build:
      context: ./backend/stats
      dockerfile: Dockerfile
    volumes:
      - stats:/app/data
    secrets:
      - stats-service-client.env
    networks:
      - pong_network
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "-s", "-o", "/dev/null"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  backend-chat:
    container_name: backend-chat
    build:
      context: ./backend/chat
      dockerfile: Dockerfile
    volumes:
      # - /app/node_modules
      # - ./:/app
      - db-data:/db
    secrets:
      - chat-service-client.env
    networks:
      - pong_network
    init: true
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    restart: unless-stopped
    working_dir: /app

secrets:
  # JWT Keys
  user-session-private.pem:
    file: ../secrets/user-session-private.pem
  user-session-public.pem:
    file: ../secrets/user-session-public.pem
  game-session-private.pem:
    file: ../secrets/game-session-private.pem
  game-session-public.pem:
    file: ../secrets/game-session-public.pem
  internal-access-private.pem:
    file: ../secrets/internal-access-private.pem
  internal-access-public.pem:
    file: ../secrets/internal-access-public.pem
  
  # Client Credentials
  users-service-client.env:
    file: ../secrets/users-service-client.env
  game-service-client.env:
    file: ../secrets/game-service-client.env
  chat-service-client.env:
    file: ../secrets/chat-service-client.env
  stats-service-client.env:
    file: ../secrets/stats-service-client.env
  presence-service-client.env:
    file: ../secrets/presence-service-client.env

  # OAuth Credentials
  google-oauth.env:
    file: ../secrets/google-oauth.env

networks:
  pong_network:

volumes:
  ssl:
  game_sessions:
  db-data:
    driver: local
  users:
  stats: