services:

  ###########
  ## Frontend
  ###########
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4443:443"
    volumes:
      - ssl:/etc/ssl/
    networks:
      - pong_network
    init: true
    # Add healthcheck if you can
    restart: unless-stopped
    depends_on:
      - api-gateway

  ##############
  ## API Gateway
  ##############
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    networks:
      - pong_network
    init: true
    # Add healthcheck if you can
    restart: unless-stopped
    depends_on:
      - backend-game

  ###################
  ## Backend Services
  ###################
  backend-game:
    container_name: backend-game
    build:
      context: ./backend/game
      dockerfile: Dockerfile
    volumes:
      - game_sessions:/app/sessions
    secrets:
      - jwt_public_key
    environment:
      - JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public_key
    networks:
      - pong_network
    init: true
    # Add healthcheck if you can
    restart: unless-stopped

  backend-users:
    container_name: backend-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    volumes:
      - users:/app/data
    secrets:
      - jwt_public_key
    env_file: .env
    environment:
      - JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public_key
    networks:
      - pong_network
    init: true
    # Add healthcheck if you can
    restart: unless-stopped

  backend-auth:
    container_name: backend-auth
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    networks:
      - pong_network
    secrets:
      - jwt_private_key
      - jwt_public_key
    env_file: .env
    environment:
      - JWT_PRIVATE_KEY_PATH=/run/secrets/jwt_private_key
      - JWT_PUBLIC_KEY_PATH=/run/secrets/jwt_public_key
    init: true
    # Add healthcheck if you can
    restart: unless-stopped

  #   chat:
  #     build:
  #       context: ./backend/chat
  #     dockerfile: Dockerfile
  #   stats:
  #     build:
  #       context: ./backend/stats
  #     dockerfile: Dockerfile


networks:
  pong_network:

volumes:
  ssl:
  game_sessions:
  users:

secrets:
  jwt_private_key:
    file: ../secrets/jwt_private_key.pem
  jwt_public_key:
    file: ../secrets/jwt_public_key.pem